// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xaymwtshzpnxdammjwzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhheW13dHNoenBueGRhbW1qd3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0Njc4MDksImV4cCI6MjA2NTA0MzgwOX0.1CJou1MlUXzdLJmTwMEAZ5YmyQ7UtoFesKNrEDFcGHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);